security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    rest_user: { password: password123, roles: ['ROLE_API_USER'] }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

    access_control:
#        - { path: ^/, roles: ROLE_API_USER }
